version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3040:3040"
    environment:
      - NODE_ENV=production
      - PORT=3040

  database:
    image: mongo:latest # Imagem do MongoDB
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    ports:
      - "27017:27017" # Porta padrão do MongoDB

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - PORT=3005

    volumes:
      - /app/node_modules
      - .:/app
