version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3040:3040"
    environment:
      - NODE_ENV=production
      - PORT=3040      
      - DATABASE_URL=mongodb://root:root123@mongodb:27017

  database:
    image: mongo:latest # Imagem do MongoDB
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    ports:
      - "27017:27017" # Porta padrão do MongoDB

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
      - PORT=3005
      - NEXT_PUBLIC_API_URL=http://localhost:3040/api
      - API_URL=http://localhost:3040/api

    volumes:
      - /app/node_modules
      - .:/app
