version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3040:3040"
    environment:
      - NODE_ENV=production
      - PORT=3040

  database:
    image: mongo:latest # Imagem do MongoDB
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=seu_usuario
      - MONGO_INITDB_ROOT_PASSWORD=sua_senha
    ports:
      - "27017:27017" # Porta padrão do MongoDB

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

    volumes:
